import Colors from "@/constants/Colors";
import { StyleSheet } from "react-native";

export const index_styles = StyleSheet.create({
  container: {
    height: "100%",
    paddingTop: 10,
    backgroundColor: Colors.forest_green,
  },
  title: {
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "center",
    color: Colors.white,
    paddingBottom: 20,
  },
  current_category: {
    backgroundColor: Colors.forest_green,
    paddingBottom: 10,
  },
  lotto_category: {
    color: Colors.light_grey,
    fontSize: 20,
    paddingLeft: 20,
  },
  lotto_prize: {
    color: Colors.white,
    textAlign: "center",
    fontSize: 30,
    paddingBottom: 10,
  },
  input_form_container: {
    height: "100%",
    padding: 20,
    backgroundColor: Colors.light_blue_green,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
  },
  options_container: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-end",
    backgroundColor: Colors.light_blue_green,
    paddingBottom: 30,
    zIndex: 5,
  },
  input_text_container: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    backgroundColor: Colors.light_blue_green,
    zIndex: 0,
  },
  submit_input_container: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    backgroundColor: "transparent",
    marginTop: 10,
  },
  input_options_button: {
    height: 50,
    padding: 10,
    marginLeft: 10,
    backgroundColor: Colors.grey,
    borderRadius: 10,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  input_options_picker: {
    height: 20,
    width: 120,
    marginLeft: 10,
    backgroundColor: Colors.grey,
    color: Colors.light_grey,
    borderRadius: 10,
    borderWidth: 0,
    zIndex: 10,
    
  },
  combinations_container: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-evenly",
    backgroundColor: Colors.light_blue_green,
    paddingBottom: 10,
  },
  input_text_button: {
    height: 40,
    backgroundColor: Colors.grey,
    borderRadius: 10,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: 100,
  },
  clear_text_button: {
    height: 40,
    backgroundColor: Colors.red,
    borderRadius: 10,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: 100,
  },
  input_text: {
    
    width: "10%",
    borderWidth: 1,
    borderColor: Colors.light_grey,
    color: "white",
    height: 40,
    borderRadius: 10,
    padding: 10,
    textAlign: "center",
  },
  result_container: {
    backgroundColor: Colors.light_blue_green,
    padding: 20,
  },
  winning_combinations_container: {
    backgroundColor: Colors.light_blue_green,
    padding: 20,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-around",
  },
  correct_number_container: {
    width: 40,
    height: 40,
    borderRadius: 20,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: Colors.green,
  },
  incorrect_number_container: {
    width: 40,
    height: 40,
    borderRadius: 20,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: Colors.red,
  },
  white_text: {
    color: Colors.white,
  },
  light_grey_text: {
    color: Colors.light_grey,
  },
  prize_won_text: {
    color: Colors.white,
    textAlign: "center",
    fontSize: 30,
    paddingTop: 20,
  },
  transparent_background: {
    backgroundColor: "transparent",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
  },
  category_dropdown: {
    backgroundColor: Colors.forest_green,
    alignItems: "flex-end",
    borderWidth: 1,
    borderColor: Colors.light_blue_green,
    width: 75,
  },
  data_status: {
    color: Colors.light_grey,
    fontSize: 20,
    paddingLeft: 20,
    textAlign: "center",
  },
  data_status_input_container: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    backgroundColor: Colors.light_blue_green,
    marginTop: 20,
    padding: 20,
  }
});
